#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Find commit files
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs front/node_modules/.bin/prettier --ignore-unknown --write

cd front && echo 'Prettier Apply Before Commit' && npx lint-staged && cd ..
